name: medikidz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management (dipakai di semua Controller)
  get: ^4.6.6
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  # HTTP client (dipakai register_service.dart & otp_service.dart untuk panggil Cloud Functions)
  http: ^1.2.0
  flutter_svg: ^2.3.0
  image_picker: ^0.8.7+5
  firebase_storage: ^12.3.2
  imgbb: 0.0.1-beta
  flutter_image_compress: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:  # --- PENGATURAN ASET DIAKTIFKAN DI SINI --- (assets dari tim-frontend)
    - assets/onboarding1.svg
    - assets/onboarding2.svg
    - assets/onboarding3.svg
    - assets/logo.png