name: medikidz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State management (dipakai di semua Controller)
  get: ^4.6.6
  # Storage lokal untuk simpan data bookmark/pilihan user
  get_storage: ^2.1.1
  # Firebase
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.2.0
  # HTTP client (dipakai register_service.dart & otp_service.dart untuk panggil Cloud Functions)
  http: ^1.2.0
  flutter_svg: ^2.3.0
  image_picker: ^0.8.7+5
  firebase_storage: ^13.4.6
  imgbb: 0.0.1-beta
  flutter_image_compress: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:  # --- PENGATURAN ASET DIAKTIFKAN DI SINI --- (assets dari tim-frontend)
    - assets/onboarding1.svg
    - assets/onboarding2.svg
    - assets/onboarding3.svg
    - assets/logo.png
    - assets/logo2.png
    - assets/logoartikel.png
    - assets/logobayi.png
    - assets/logohubungiklinik.png
    - assets/logojadwalimunisasi.png
    - assets/logoriwayatimunisasi.png