// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvOJU8nXrKFh6g-QaAsJtHs1HpmyvV90',
    appId: '1:1076259151720:web:bedeb4f70d783b227340dd',
    messagingSenderId: '1076259151720',
    projectId: 'project-medikidz',
    authDomain: 'project-medikidz.firebaseapp.com',
    storageBucket: 'project-medikidz.firebasestorage.app',
    measurementId: 'G-0G220BFFES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuI9xX0xj4tiLgQCe3R8AbD3XW_fFjDOM',
    appId: '1:1076259151720:android:108f7c161a2e16207340dd',
    messagingSenderId: '1076259151720',
    projectId: 'project-medikidz',
    storageBucket: 'project-medikidz.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBB5iObIhL_sBHcDGmKCCXbmOCf5KmCD8',
    appId: '1:1076259151720:ios:12672c445279efd07340dd',
    messagingSenderId: '1076259151720',
    projectId: 'project-medikidz',
    storageBucket: 'project-medikidz.firebasestorage.app',
    iosBundleId: 'com.example.medikidz',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBB5iObIhL_sBHcDGmKCCXbmOCf5KmCD8',
    appId: '1:1076259151720:ios:12672c445279efd07340dd',
    messagingSenderId: '1076259151720',
    projectId: 'project-medikidz',
    storageBucket: 'project-medikidz.firebasestorage.app',
    iosBundleId: 'com.example.medikidz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvOJU8nXrKFh6g-QaAsJtHs1HpmyvV90',
    appId: '1:1076259151720:web:b5f922476cb9967a7340dd',
    messagingSenderId: '1076259151720',
    projectId: 'project-medikidz',
    authDomain: 'project-medikidz.firebaseapp.com',
    storageBucket: 'project-medikidz.firebasestorage.app',
    measurementId: 'G-Y9NN90WGYM',
  );
}
